name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: 빌드 및 테스트
        run: ./gradlew build

      - name: S3 버킷에 이진 파일 업로드
        uses: actions/aws/cli@master
        with:
          cli-command: s3 sync
          cli-subcommand: .
          cli-arguments: ${{ secrets.S3_BUCKET_NAME }} --acl public-read --delete --exclude "*" --include "*.html" --include "*.css" --include "*.js"

      - name: CloudFront 캐시 무효화
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution: ${{ secrets.CDN_DISTRIBUTION_ID }}
          paths: '/*'
        continue-on-error: true