name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: gradlew에 대한 실행 권한 부여
        run: chmod +x gradlew

      - name: 빌드 및 테스트
        continue-on-error: true
        run: ./gradlew build

      - name: S3에 파일 업로드 - 1
        uses: docker://amazon/aws-cli:2.0.7
        with:
          args: s3 sync ./src/main/resources/static s3://${{ secrets.S3_BUCKET_NAME }}

      - name: S3에 파일 업로드 - 2
        uses: docker://amazon/aws-cli:2.0.7
        with:
          args: s3 sync ./src/main/resources/templates s3://${{ secrets.S3_BUCKET_NAME }}

      - name: CloudFront 캐시 무효화
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution: ${{ secrets.CDN_DISTRIBUTION_ID }}
          paths: '/*'
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}