name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: gradlew에 대한 실행 권한 부여
        run: chmod +x gradlew

      - name: 빌드 및 테스트
        continue-on-error: true
        run: ./gradlew build

      - name: AWS 자격 증명 구성
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3에 파일 업로드 - 1
        run: aws s3 sync ./src/main/resources/static s3://${{ secrets.S3_BUCKET_NAME }}

      - name: S3에 파일 업로드 - 2
        run: aws s3 sync ./src/main/resources/templates s3://${{ secrets.S3_BUCKET_NAME }}

      - name: CloudFront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID }} --paths "/*"
